# Generated by Django 4.2.10 on 2024-03-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='addres',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес пользователя'),
        ),
    ]
