# Generated by Django 4.2.11 on 2024-05-12 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailmailinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Текст письма')),
                ('img', models.ImageField(blank=True, null=True, upload_to='email_mailing', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Фото')),
                ('time_sending', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'Сохранение письма',
                'verbose_name_plural': 'Сохранение письм',
                'db_table': 'app_email_mailing',
            },
        ),
    ]
