# Generated by Django 4.2.11 on 2024-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='Addresses',
            field=models.TextField(default='напишите адрес', verbose_name='Адрес'),
        ),
    ]
