# Generated by Django 4.2.11 on 2024-04-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorproduct',
            name='image_color',
            field=models.ImageField(blank=True, null=True, upload_to='image_color', verbose_name='Фото цвета'),
        ),
    ]
