# Generated by Django 4.2.11 on 2024-04-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_colorproduct_image_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeproduct',
            name='size',
            field=models.PositiveIntegerField(verbose_name='Размер'),
        ),
    ]
