# Generated by Django 4.2.11 on 2024-05-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_sizeproduct_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='imageproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sizeproduct',
            name='color',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id', 'name', 'price'), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Скидка в %'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='product_images', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Размер'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'description'], name='app_product_name_6b8cd3_idx'),
        ),
        migrations.DeleteModel(
            name='ColorProduct',
        ),
        migrations.DeleteModel(
            name='ImageProduct',
        ),
        migrations.DeleteModel(
            name='SizeProduct',
        ),
    ]
