# Generated by Django 4.2.10 on 2024-03-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='index_images/banners', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'db_table': 'banner_index',
            },
        ),
        migrations.CreateModel(
            name='StocksIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('above_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст сверху над зоголовком')),
                ('text', models.CharField(max_length=155, verbose_name='Текст акции')),
                ('description_text', models.CharField(max_length=250, verbose_name='Описание акции')),
                ('text_button', models.CharField(max_length=50, verbose_name='Текст кнопки')),
                ('image', models.ImageField(upload_to='index_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Название акции',
                'verbose_name_plural': 'Названия акции',
                'db_table': 'stocks_index',
            },
        ),
    ]
