# Generated by Django 4.2.10 on 2024-03-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Популярный товар',
                'verbose_name_plural': 'Популярные товары',
                'db_table': 'popular_items',
            },
        ),
        migrations.CreateModel(
            name='PopularItemsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Название популярных товаров')),
            ],
            options={
                'verbose_name': 'Название популярных товаров',
                'verbose_name_plural': 'Названия популярных товаров',
                'db_table': 'popular_items_title',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PopularItemsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_page', models.PositiveIntegerField(default=0, verbose_name='Количество товара на 1 категории')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.popularitems', verbose_name='Категория товаров')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Популярный товар',
                'verbose_name_plural': 'Популярные товары',
                'db_table': 'popular_items_product',
            },
        ),
        migrations.AddField(
            model_name='popularitems',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.popularitemstitle', verbose_name='Название популярных категорий'),
        ),
    ]
