# Generated by Django 4.2.10 on 2024-03-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_popularitems_popularitemstitle_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularitems',
            name='title',
        ),
    ]
