# Generated by Django 4.2.10 on 2024-03-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_popularitems_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на социальную сеть')),
                ('name', models.CharField(max_length=100, verbose_name='Название социальной сети')),
                ('image', models.ImageField(upload_to='index_images/social_network', verbose_name='Изображение(svg format)')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
                'db_table': 'social_network',
            },
        ),
    ]
