# Generated by Django 4.2.10 on 2024-03-16 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_socialnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='image',
            field=models.ImageField(upload_to='index_images/social_network', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Изображение(svg format)'),
        ),
    ]
